### ISSUE TITLE
Getting Started Help

### ISSUE THREAD

**Issue by grahambates-code** [clockwork-dog/cogs-client-react-lib#80]
I am a developer trying to integrate some React components with COGS but have been struggling with the limited documentation on this project. 

Can you consider adding a few lines to assist other developers to outline what the project is for, and how the developer should be working.

For example, some core things I am unclear on - should I be colocated on the same LAN as the COGS server? Where do I set the IP address? Or does the 'simulator' act as a Cogs server? 

Can I send receive data from Cogs (Eg hints) and can I send data (Eg lights) both via a React application? If not, what is this library for?

**Comment by chetbox** [comment]
Hi @grahambates-code, thanks for the feedback. 

> I am a developer trying to integrate some React components with COGS but have been struggling with the limited documentation on this project.
>
> Can you consider adding a few lines to assist other developers to outline what the project is for, and how the developer should be working.

Our docs are spread a little and we're working on unifying everything to make it easier to get started.

The quickest way to get set up is with our Create React App Template: https://github.com/clockwork-dog/cra-template-cogs-client

If you're setting up manually there is some help in the README in this repo and some additional setup details here:
https://docs.cogs.show/plugins/custom/

> For example, some core things I am unclear on - should I be colocated on the same LAN as the COGS server? Where do I set the IP address? Or does the 'simulator' act as a Cogs server?

Yes, you should be on the same LAN. The Media Master and COGS communicate via local network IP addresses. The Media Master will be assigned an IP address by your network router. If the IP address of you Media Master changes COGS will handle this.

> Can I send receive data from Cogs (Eg hints) and can I send data (Eg lights) both via a React application? If not, what is this library for?

Yes! The Custom Content example project shows you how to use "states" or "events" to communicate back and forth to COGS. https://docs.cogs.show/examples/#custom-content

**Comment by grahambates-code** [comment]
Brilliant, I've got most of it working now combining this project and the one you mentioned, very very cool.
